apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: default
spec:
  storageClassName: "my-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi